version: "3.9"
services:
  web:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
