# Generated by Django 5.2 on 2025-04-04 04:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('ef1188f6-420c-4cce-a66c-a36b3604434f'), primary_key=True, serialize=False),
        ),
    ]
