# Generated by Django 5.2 on 2025-04-04 04:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('75fefc2f-20cc-4ba1-a1c1-4b2574f7a2dd'), primary_key=True, serialize=False),
        ),
    ]
